spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mail configuration
spring.mail.host=smtp.gmail.com
#Use port 2525 if 587 is not working
spring.mail.port=2525
spring.mail.username=agrigovnotify@gmail.com
spring.mail.password=grisokrawajsnylf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
